# noinspection SqlNoDataSourceInspectionForFile

INSERT INTO utilisateur VALUES (DEFAULT, 'b.alarie', 'Secret59003', 0, 'Alarie, Benoît', 'b.alarie@cavenir.qc.ca'),
  (DEFAULT, 'd.bessette', 'Secret51412', 0, 'Bessette, Danielle', 'd.bessette@cavenir.qc.ca'),
  (DEFAULT, 'c.boivert', 'Secret14270', 0, 'Boivert, Charlène', 'c.boivert@cavenir.qc.ca'),
  (DEFAULT, 'g.bouchard', 'Secret14379', 0, 'Bouchard, Geneviève', 'g.bouchard@cavenir.qc.ca'),
  (DEFAULT, 'd.boyce', 'Secret24590', 0, 'Boyce, Dominique', 'd.boyce@cavenir.qc.ca'),
  (DEFAULT, 'l.brodeur', 'Secret12345', 1, 'Brodeur, Louis', 'l.brodeur@cavenir.qc.ca'),
  (DEFAULT, 'd.caron', 'Secret77489', 0, 'Caron, Dany', 'd.caron@cavenir.qc.ca'),
  (DEFAULT, 'l.caron', 'Secret12345', 1, 'Caron, Lise', 'l.caron@cavenir.qc.ca'),
  (DEFAULT, 'b.chabotgiguere', 'Secret31309', 0, 'Chabot-Giguère, Brigitte', 'b.chabot-giguere@cavenir.qc.ca'),
  (DEFAULT, 'b.dalemans', 'Secret13917', 0, 'Dalemans, Bernice', 'b.dalemans@cavenir.qc.ca'),
  (DEFAULT, 'j.delmotte', 'Secret58382', 0, 'Delmotte, Jacinthe', 'j.delmotte@cavenir.qc.ca'),
  (DEFAULT, 'j.desmarais', 'Secret94779', 0, 'Desmarais, Jannie', 'j.desmarais@cavenir.qc.ca'),
  (DEFAULT, 'm.desrochers', 'Secret77416', 0, 'Desrochers, Mélanie', 'm.desrochers@cavenir.qc.ca'),
  (DEFAULT, 'k.doin', 'Secret58366', 0, 'Doin, Karine', 'k.doin@cavenir.qc.ca'),
  (DEFAULT, 'j.dufresne', 'Secret57785', 0, 'Dufresne, Josée', 'j.dufresne@cavenir.qc.ca'),
  (DEFAULT, 'jf.giroux', 'Secret64343', 0, 'Giroux, Jean-François', 'jf.giroux@cavenir.qc.ca'),
  (DEFAULT, 's.grisetetrault', 'Secret53737', 0, 'Grisé-Tétrault, Simon', 's.grise-tetrault@cavenir.qc.ca'),
  (DEFAULT, 'j.hubert', 'Secret12345', 1, 'Hubert, Jacqueline', 'j.hubert@cavenir.qc.ca'),
  (DEFAULT, 's.julien', 'Secret17638', 0, 'Julien, Sonia', 's.julien@cavenir.qc.ca'),
  (DEFAULT, 'n.laliberte', 'Secret18428', 0, 'Laliberté, Nicole', 'n.laliberte@cavenir.qc.ca'),
  (DEFAULT, 's.lamarche', 'Secret46088', 0, 'Lamarche, Sophie', 's.lamarche@cavenir.qc.ca'),
  (DEFAULT, 'p.lamarre', 'Secret12345', 1, 'Lamarre, Pierre', 'p.lamarre@cavenir.qc.ca'),
  (DEFAULT, 'a.lanctotvillemure', 'Secret96703', 0, 'Lanctôt-Villemure, Alexandre', 'a.lanctot-villemure@cavenir.qc.ca'),
  (DEFAULT, 'm.lapierre', 'Secret81822', 0, 'Lapierre, Mélanie', 'm.lapierre@cavenir.qc.ca'),
  (DEFAULT, 'k.lavallee', 'Secret74275', 0, 'Lavallée, Katia', 'k.lavallee@cavenir.qc.ca'),
  (DEFAULT, 'a.leclerc', 'Secret12345', 1, 'Leclerc, Alain', 'a.leclerc@cavenir.qc.ca'),
  (DEFAULT, 's.lemieux', 'Secret31225', 0, 'Lemieux, Sylvain', 's.lemieux@cavenir.qc.ca'),
  (DEFAULT, 'v.lento', 'Secret81297', 0, 'Lento, Valérie', 'v.lento@cavenir.qc.ca'),
  (DEFAULT, 'me.locasbourcier', 'Secret65628', 0, 'Locas-Bourcier, Marie-Ève', 'me.locas-bourcier@cavenir.qc.ca'),
  (DEFAULT, 'mc.maltais', 'Secret57215', 0, 'Maltais, Marie-Claude', 'mc.maltais@cavenir.qc.ca'),
  (DEFAULT, 'a.milos', 'Secret12345', 1, 'Milos, Amir', 'a.milos@cavenir.qc.ca'),
  (DEFAULT, 'ml.morin', 'Secret99016', 0, 'Morin, Marie-Line', 'ml.morin@cavenir.qc.ca'),
  (DEFAULT, 'hp.nguyen', 'Secret12345', 1, 'Nguyen, Huu Phuoc', 'hp.nguyen@cavenir.qc.ca'),
  (DEFAULT, 'mj.ouellette', 'Secret78328', 0, 'Ouellette, Marie-Josée', 'mj.ouellette@cavenir.qc.ca'),
  (DEFAULT, 'a.ouimet', 'Secret48179', 0, 'Ouimet, Alexandra', 'a.ouimet@cavenir.qc.ca'),
  (DEFAULT, 'mj.patry', 'Secret49222', 0, 'Patry, Marie-Josée', 'mj.patry@cavenir.qc.ca'),
  (DEFAULT, 'aa.picard', 'Secret50895', 0, 'Picard, Andrée-Anne', 'aa.picard@cavenir.qc.ca'),
  (DEFAULT, 'a.rivard', 'Secret50855', 0, 'Rivard, Astrid', 'a.rivard@cavenir.qc.ca'),
  (DEFAULT, 'a.rousson', 'Secret98757', 0, 'Rousson, Audrey', 'a.rousson@cavenir.qc.ca')